#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DMS")]
	public partial class LinqSQLDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETHOSO(CHITIETHOSO instance);
    partial void UpdateCHITIETHOSO(CHITIETHOSO instance);
    partial void DeleteCHITIETHOSO(CHITIETHOSO instance);
    partial void InsertVANBANDI(VANBANDI instance);
    partial void UpdateVANBANDI(VANBANDI instance);
    partial void DeleteVANBANDI(VANBANDI instance);
    partial void InsertDANHMUC(DANHMUC instance);
    partial void UpdateDANHMUC(DANHMUC instance);
    partial void DeleteDANHMUC(DANHMUC instance);
    partial void InsertHOSO(HOSO instance);
    partial void UpdateHOSO(HOSO instance);
    partial void DeleteHOSO(HOSO instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void InsertPHONGBAN(PHONGBAN instance);
    partial void UpdatePHONGBAN(PHONGBAN instance);
    partial void DeletePHONGBAN(PHONGBAN instance);
    partial void InsertVANBANDEN(VANBANDEN instance);
    partial void UpdateVANBANDEN(VANBANDEN instance);
    partial void DeleteVANBANDEN(VANBANDEN instance);
    #endregion
		
		public LinqSQLDataDataContext() : 
				base(global::DAO.Properties.Settings.Default.DMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqSQLDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqSQLDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqSQLDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqSQLDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETHOSO> CHITIETHOSOs
		{
			get
			{
				return this.GetTable<CHITIETHOSO>();
			}
		}
		
		public System.Data.Linq.Table<VANBANDI> VANBANDIs
		{
			get
			{
				return this.GetTable<VANBANDI>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUC> DANHMUCs
		{
			get
			{
				return this.GetTable<DANHMUC>();
			}
		}
		
		public System.Data.Linq.Table<HOSO> HOSOs
		{
			get
			{
				return this.GetTable<HOSO>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
		
		public System.Data.Linq.Table<VANBANDEN> VANBANDENs
		{
			get
			{
				return this.GetTable<VANBANDEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOSO")]
	public partial class CHITIETHOSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idhoso;
		
		private System.Nullable<int> _maNV;
		
		private System.Nullable<System.DateTime> _ngaybanhanh;
		
		private string _sokyhieuvanban;
		
		private string _trichyeuvanban;
		
		private System.Nullable<int> _loaivanbandenhaydi;
		
		private System.Nullable<int> _thutuvanban;
		
		private EntityRef<HOSO> _HOSO;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidhosoChanging(System.Nullable<int> value);
    partial void OnidhosoChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    partial void OnngaybanhanhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybanhanhChanged();
    partial void OnsokyhieuvanbanChanging(string value);
    partial void OnsokyhieuvanbanChanged();
    partial void OntrichyeuvanbanChanging(string value);
    partial void OntrichyeuvanbanChanged();
    partial void OnloaivanbandenhaydiChanging(System.Nullable<int> value);
    partial void OnloaivanbandenhaydiChanged();
    partial void OnthutuvanbanChanging(System.Nullable<int> value);
    partial void OnthutuvanbanChanged();
    #endregion
		
		public CHITIETHOSO()
		{
			this._HOSO = default(EntityRef<HOSO>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhoso", DbType="Int")]
		public System.Nullable<int> idhoso
		{
			get
			{
				return this._idhoso;
			}
			set
			{
				if ((this._idhoso != value))
				{
					if (this._HOSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidhosoChanging(value);
					this.SendPropertyChanging();
					this._idhoso = value;
					this.SendPropertyChanged("idhoso");
					this.OnidhosoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybanhanh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybanhanh
		{
			get
			{
				return this._ngaybanhanh;
			}
			set
			{
				if ((this._ngaybanhanh != value))
				{
					this.OnngaybanhanhChanging(value);
					this.SendPropertyChanging();
					this._ngaybanhanh = value;
					this.SendPropertyChanged("ngaybanhanh");
					this.OnngaybanhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sokyhieuvanban", DbType="VarChar(20)")]
		public string sokyhieuvanban
		{
			get
			{
				return this._sokyhieuvanban;
			}
			set
			{
				if ((this._sokyhieuvanban != value))
				{
					this.OnsokyhieuvanbanChanging(value);
					this.SendPropertyChanging();
					this._sokyhieuvanban = value;
					this.SendPropertyChanged("sokyhieuvanban");
					this.OnsokyhieuvanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trichyeuvanban", DbType="VarChar(250)")]
		public string trichyeuvanban
		{
			get
			{
				return this._trichyeuvanban;
			}
			set
			{
				if ((this._trichyeuvanban != value))
				{
					this.OntrichyeuvanbanChanging(value);
					this.SendPropertyChanging();
					this._trichyeuvanban = value;
					this.SendPropertyChanged("trichyeuvanban");
					this.OntrichyeuvanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaivanbandenhaydi", DbType="Int")]
		public System.Nullable<int> loaivanbandenhaydi
		{
			get
			{
				return this._loaivanbandenhaydi;
			}
			set
			{
				if ((this._loaivanbandenhaydi != value))
				{
					this.OnloaivanbandenhaydiChanging(value);
					this.SendPropertyChanging();
					this._loaivanbandenhaydi = value;
					this.SendPropertyChanged("loaivanbandenhaydi");
					this.OnloaivanbandenhaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thutuvanban", DbType="Int")]
		public System.Nullable<int> thutuvanban
		{
			get
			{
				return this._thutuvanban;
			}
			set
			{
				if ((this._thutuvanban != value))
				{
					this.OnthutuvanbanChanging(value);
					this.SendPropertyChanging();
					this._thutuvanban = value;
					this.SendPropertyChanged("thutuvanban");
					this.OnthutuvanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO_CHITIETHOSO", Storage="_HOSO", ThisKey="idhoso", OtherKey="id_hoso", IsForeignKey=true)]
		public HOSO HOSO
		{
			get
			{
				return this._HOSO.Entity;
			}
			set
			{
				HOSO previousValue = this._HOSO.Entity;
				if (((previousValue != value) 
							|| (this._HOSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSO.Entity = null;
						previousValue.CHITIETHOSOs.Remove(this);
					}
					this._HOSO.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOSOs.Add(this);
						this._idhoso = value.id_hoso;
					}
					else
					{
						this._idhoso = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOSO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CHITIETHOSO", Storage="_NHANVIEN", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.CHITIETHOSOs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOSOs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDI")]
	public partial class VANBANDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vanbandi;
		
		private string _kyhieuvanban;
		
		private System.Nullable<System.DateTime> _ngaybanhanh;
		
		private string _loaivanban;
		
		private string _trichyeu;
		
		private string _sovanban;
		
		private string _linhvuc;
		
		private string _dokhan;
		
		private string _soban;
		
		private string _sotrang;
		
		private string _filedinhkem;
		
		private string _nguoisoan;
		
		private string _nguoiky;
		
		private string _noinhan;
		
		private System.Nullable<byte> _xuly;
		
		private string _quyenxem;
		
		private string _luu;
		
		private System.Nullable<int> _maNV;
		
		private EntitySet<DANHMUC> _DANHMUCs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vanbandiChanging(int value);
    partial void Onid_vanbandiChanged();
    partial void OnkyhieuvanbanChanging(string value);
    partial void OnkyhieuvanbanChanged();
    partial void OnngaybanhanhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybanhanhChanged();
    partial void OnloaivanbanChanging(string value);
    partial void OnloaivanbanChanged();
    partial void OntrichyeuChanging(string value);
    partial void OntrichyeuChanged();
    partial void OnsovanbanChanging(string value);
    partial void OnsovanbanChanged();
    partial void OnlinhvucChanging(string value);
    partial void OnlinhvucChanged();
    partial void OndokhanChanging(string value);
    partial void OndokhanChanged();
    partial void OnsobanChanging(string value);
    partial void OnsobanChanged();
    partial void OnsotrangChanging(string value);
    partial void OnsotrangChanged();
    partial void OnfiledinhkemChanging(string value);
    partial void OnfiledinhkemChanged();
    partial void OnnguoisoanChanging(string value);
    partial void OnnguoisoanChanged();
    partial void OnnguoikyChanging(string value);
    partial void OnnguoikyChanged();
    partial void OnnoinhanChanging(string value);
    partial void OnnoinhanChanged();
    partial void OnxulyChanging(System.Nullable<byte> value);
    partial void OnxulyChanged();
    partial void OnquyenxemChanging(string value);
    partial void OnquyenxemChanged();
    partial void OnluuChanging(string value);
    partial void OnluuChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    #endregion
		
		public VANBANDI()
		{
			this._DANHMUCs = new EntitySet<DANHMUC>(new Action<DANHMUC>(this.attach_DANHMUCs), new Action<DANHMUC>(this.detach_DANHMUCs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vanbandi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_vanbandi
		{
			get
			{
				return this._id_vanbandi;
			}
			set
			{
				if ((this._id_vanbandi != value))
				{
					this.Onid_vanbandiChanging(value);
					this.SendPropertyChanging();
					this._id_vanbandi = value;
					this.SendPropertyChanged("id_vanbandi");
					this.Onid_vanbandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kyhieuvanban", DbType="VarChar(50)")]
		public string kyhieuvanban
		{
			get
			{
				return this._kyhieuvanban;
			}
			set
			{
				if ((this._kyhieuvanban != value))
				{
					this.OnkyhieuvanbanChanging(value);
					this.SendPropertyChanging();
					this._kyhieuvanban = value;
					this.SendPropertyChanged("kyhieuvanban");
					this.OnkyhieuvanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybanhanh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybanhanh
		{
			get
			{
				return this._ngaybanhanh;
			}
			set
			{
				if ((this._ngaybanhanh != value))
				{
					this.OnngaybanhanhChanging(value);
					this.SendPropertyChanging();
					this._ngaybanhanh = value;
					this.SendPropertyChanged("ngaybanhanh");
					this.OnngaybanhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaivanban", DbType="VarChar(50)")]
		public string loaivanban
		{
			get
			{
				return this._loaivanban;
			}
			set
			{
				if ((this._loaivanban != value))
				{
					this.OnloaivanbanChanging(value);
					this.SendPropertyChanging();
					this._loaivanban = value;
					this.SendPropertyChanged("loaivanban");
					this.OnloaivanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trichyeu", DbType="VarChar(250)")]
		public string trichyeu
		{
			get
			{
				return this._trichyeu;
			}
			set
			{
				if ((this._trichyeu != value))
				{
					this.OntrichyeuChanging(value);
					this.SendPropertyChanging();
					this._trichyeu = value;
					this.SendPropertyChanged("trichyeu");
					this.OntrichyeuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sovanban", DbType="VarChar(100)")]
		public string sovanban
		{
			get
			{
				return this._sovanban;
			}
			set
			{
				if ((this._sovanban != value))
				{
					this.OnsovanbanChanging(value);
					this.SendPropertyChanging();
					this._sovanban = value;
					this.SendPropertyChanged("sovanban");
					this.OnsovanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linhvuc", DbType="VarChar(50)")]
		public string linhvuc
		{
			get
			{
				return this._linhvuc;
			}
			set
			{
				if ((this._linhvuc != value))
				{
					this.OnlinhvucChanging(value);
					this.SendPropertyChanging();
					this._linhvuc = value;
					this.SendPropertyChanged("linhvuc");
					this.OnlinhvucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dokhan", DbType="VarChar(50)")]
		public string dokhan
		{
			get
			{
				return this._dokhan;
			}
			set
			{
				if ((this._dokhan != value))
				{
					this.OndokhanChanging(value);
					this.SendPropertyChanging();
					this._dokhan = value;
					this.SendPropertyChanged("dokhan");
					this.OndokhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soban", DbType="VarChar(10)")]
		public string soban
		{
			get
			{
				return this._soban;
			}
			set
			{
				if ((this._soban != value))
				{
					this.OnsobanChanging(value);
					this.SendPropertyChanging();
					this._soban = value;
					this.SendPropertyChanged("soban");
					this.OnsobanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotrang", DbType="VarChar(10)")]
		public string sotrang
		{
			get
			{
				return this._sotrang;
			}
			set
			{
				if ((this._sotrang != value))
				{
					this.OnsotrangChanging(value);
					this.SendPropertyChanging();
					this._sotrang = value;
					this.SendPropertyChanged("sotrang");
					this.OnsotrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filedinhkem", DbType="VarChar(250)")]
		public string filedinhkem
		{
			get
			{
				return this._filedinhkem;
			}
			set
			{
				if ((this._filedinhkem != value))
				{
					this.OnfiledinhkemChanging(value);
					this.SendPropertyChanging();
					this._filedinhkem = value;
					this.SendPropertyChanged("filedinhkem");
					this.OnfiledinhkemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoisoan", DbType="VarChar(100)")]
		public string nguoisoan
		{
			get
			{
				return this._nguoisoan;
			}
			set
			{
				if ((this._nguoisoan != value))
				{
					this.OnnguoisoanChanging(value);
					this.SendPropertyChanging();
					this._nguoisoan = value;
					this.SendPropertyChanged("nguoisoan");
					this.OnnguoisoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiky", DbType="VarChar(100)")]
		public string nguoiky
		{
			get
			{
				return this._nguoiky;
			}
			set
			{
				if ((this._nguoiky != value))
				{
					this.OnnguoikyChanging(value);
					this.SendPropertyChanging();
					this._nguoiky = value;
					this.SendPropertyChanged("nguoiky");
					this.OnnguoikyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noinhan", DbType="VarChar(250)")]
		public string noinhan
		{
			get
			{
				return this._noinhan;
			}
			set
			{
				if ((this._noinhan != value))
				{
					this.OnnoinhanChanging(value);
					this.SendPropertyChanging();
					this._noinhan = value;
					this.SendPropertyChanged("noinhan");
					this.OnnoinhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuly", DbType="TinyInt")]
		public System.Nullable<byte> xuly
		{
			get
			{
				return this._xuly;
			}
			set
			{
				if ((this._xuly != value))
				{
					this.OnxulyChanging(value);
					this.SendPropertyChanging();
					this._xuly = value;
					this.SendPropertyChanged("xuly");
					this.OnxulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenxem", DbType="VarChar(100)")]
		public string quyenxem
		{
			get
			{
				return this._quyenxem;
			}
			set
			{
				if ((this._quyenxem != value))
				{
					this.OnquyenxemChanging(value);
					this.SendPropertyChanging();
					this._quyenxem = value;
					this.SendPropertyChanged("quyenxem");
					this.OnquyenxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luu", DbType="VarChar(100)")]
		public string luu
		{
			get
			{
				return this._luu;
			}
			set
			{
				if ((this._luu != value))
				{
					this.OnluuChanging(value);
					this.SendPropertyChanging();
					this._luu = value;
					this.SendPropertyChanged("luu");
					this.OnluuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VANBANDI_DANHMUC", Storage="_DANHMUCs", ThisKey="id_vanbandi", OtherKey="idvanbandi")]
		public EntitySet<DANHMUC> DANHMUCs
		{
			get
			{
				return this._DANHMUCs;
			}
			set
			{
				this._DANHMUCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VANBANDI", Storage="_NHANVIEN", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.VANBANDIs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.VANBANDIs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHMUCs(DANHMUC entity)
		{
			this.SendPropertyChanging();
			entity.VANBANDI = this;
		}
		
		private void detach_DANHMUCs(DANHMUC entity)
		{
			this.SendPropertyChanging();
			entity.VANBANDI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUC")]
	public partial class DANHMUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDM;
		
		private string _tendanhmuc;
		
		private System.Nullable<int> _loaidanhmuc;
		
		private System.Nullable<byte> _trangthaidanhmuc;
		
		private System.Nullable<int> _idvanbandi;
		
		private System.Nullable<int> _idvanbanden;
		
		private EntityRef<VANBANDI> _VANBANDI;
		
		private EntityRef<VANBANDEN> _VANBANDEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDMChanging(int value);
    partial void OnmaDMChanged();
    partial void OntendanhmucChanging(string value);
    partial void OntendanhmucChanged();
    partial void OnloaidanhmucChanging(System.Nullable<int> value);
    partial void OnloaidanhmucChanged();
    partial void OntrangthaidanhmucChanging(System.Nullable<byte> value);
    partial void OntrangthaidanhmucChanged();
    partial void OnidvanbandiChanging(System.Nullable<int> value);
    partial void OnidvanbandiChanged();
    partial void OnidvanbandenChanging(System.Nullable<int> value);
    partial void OnidvanbandenChanged();
    #endregion
		
		public DANHMUC()
		{
			this._VANBANDI = default(EntityRef<VANBANDI>);
			this._VANBANDEN = default(EntityRef<VANBANDEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maDM
		{
			get
			{
				return this._maDM;
			}
			set
			{
				if ((this._maDM != value))
				{
					this.OnmaDMChanging(value);
					this.SendPropertyChanging();
					this._maDM = value;
					this.SendPropertyChanged("maDM");
					this.OnmaDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendanhmuc", DbType="VarChar(255)")]
		public string tendanhmuc
		{
			get
			{
				return this._tendanhmuc;
			}
			set
			{
				if ((this._tendanhmuc != value))
				{
					this.OntendanhmucChanging(value);
					this.SendPropertyChanging();
					this._tendanhmuc = value;
					this.SendPropertyChanged("tendanhmuc");
					this.OntendanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaidanhmuc", DbType="Int")]
		public System.Nullable<int> loaidanhmuc
		{
			get
			{
				return this._loaidanhmuc;
			}
			set
			{
				if ((this._loaidanhmuc != value))
				{
					this.OnloaidanhmucChanging(value);
					this.SendPropertyChanging();
					this._loaidanhmuc = value;
					this.SendPropertyChanged("loaidanhmuc");
					this.OnloaidanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthaidanhmuc", DbType="TinyInt")]
		public System.Nullable<byte> trangthaidanhmuc
		{
			get
			{
				return this._trangthaidanhmuc;
			}
			set
			{
				if ((this._trangthaidanhmuc != value))
				{
					this.OntrangthaidanhmucChanging(value);
					this.SendPropertyChanging();
					this._trangthaidanhmuc = value;
					this.SendPropertyChanged("trangthaidanhmuc");
					this.OntrangthaidanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idvanbandi", DbType="Int")]
		public System.Nullable<int> idvanbandi
		{
			get
			{
				return this._idvanbandi;
			}
			set
			{
				if ((this._idvanbandi != value))
				{
					if (this._VANBANDI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidvanbandiChanging(value);
					this.SendPropertyChanging();
					this._idvanbandi = value;
					this.SendPropertyChanged("idvanbandi");
					this.OnidvanbandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idvanbanden", DbType="Int")]
		public System.Nullable<int> idvanbanden
		{
			get
			{
				return this._idvanbanden;
			}
			set
			{
				if ((this._idvanbanden != value))
				{
					if (this._VANBANDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidvanbandenChanging(value);
					this.SendPropertyChanging();
					this._idvanbanden = value;
					this.SendPropertyChanged("idvanbanden");
					this.OnidvanbandenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VANBANDI_DANHMUC", Storage="_VANBANDI", ThisKey="idvanbandi", OtherKey="id_vanbandi", IsForeignKey=true)]
		public VANBANDI VANBANDI
		{
			get
			{
				return this._VANBANDI.Entity;
			}
			set
			{
				VANBANDI previousValue = this._VANBANDI.Entity;
				if (((previousValue != value) 
							|| (this._VANBANDI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VANBANDI.Entity = null;
						previousValue.DANHMUCs.Remove(this);
					}
					this._VANBANDI.Entity = value;
					if ((value != null))
					{
						value.DANHMUCs.Add(this);
						this._idvanbandi = value.id_vanbandi;
					}
					else
					{
						this._idvanbandi = default(Nullable<int>);
					}
					this.SendPropertyChanged("VANBANDI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VANBANDEN_DANHMUC", Storage="_VANBANDEN", ThisKey="idvanbanden", OtherKey="sovanbanden", IsForeignKey=true)]
		public VANBANDEN VANBANDEN
		{
			get
			{
				return this._VANBANDEN.Entity;
			}
			set
			{
				VANBANDEN previousValue = this._VANBANDEN.Entity;
				if (((previousValue != value) 
							|| (this._VANBANDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VANBANDEN.Entity = null;
						previousValue.DANHMUCs.Remove(this);
					}
					this._VANBANDEN.Entity = value;
					if ((value != null))
					{
						value.DANHMUCs.Add(this);
						this._idvanbanden = value.sovanbanden;
					}
					else
					{
						this._idvanbanden = default(Nullable<int>);
					}
					this.SendPropertyChanged("VANBANDEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSO")]
	public partial class HOSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoso;
		
		private string _mahoso;
		
		private string _tieudehoso;
		
		private string _nguoilaphoso;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private string _soto;
		
		private System.Nullable<byte> _loaivanbandenhaydi;
		
		private EntitySet<CHITIETHOSO> _CHITIETHOSOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hosoChanging(int value);
    partial void Onid_hosoChanged();
    partial void OnmahosoChanging(string value);
    partial void OnmahosoChanged();
    partial void OntieudehosoChanging(string value);
    partial void OntieudehosoChanged();
    partial void OnnguoilaphosoChanging(string value);
    partial void OnnguoilaphosoChanged();
    partial void OnngaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybatdauChanged();
    partial void OnngayketthucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayketthucChanged();
    partial void OnsotoChanging(string value);
    partial void OnsotoChanged();
    partial void OnloaivanbandenhaydiChanging(System.Nullable<byte> value);
    partial void OnloaivanbandenhaydiChanged();
    #endregion
		
		public HOSO()
		{
			this._CHITIETHOSOs = new EntitySet<CHITIETHOSO>(new Action<CHITIETHOSO>(this.attach_CHITIETHOSOs), new Action<CHITIETHOSO>(this.detach_CHITIETHOSOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hoso
		{
			get
			{
				return this._id_hoso;
			}
			set
			{
				if ((this._id_hoso != value))
				{
					this.Onid_hosoChanging(value);
					this.SendPropertyChanging();
					this._id_hoso = value;
					this.SendPropertyChanged("id_hoso");
					this.Onid_hosoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoso", DbType="VarChar(20)")]
		public string mahoso
		{
			get
			{
				return this._mahoso;
			}
			set
			{
				if ((this._mahoso != value))
				{
					this.OnmahosoChanging(value);
					this.SendPropertyChanging();
					this._mahoso = value;
					this.SendPropertyChanged("mahoso");
					this.OnmahosoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieudehoso", DbType="VarChar(100)")]
		public string tieudehoso
		{
			get
			{
				return this._tieudehoso;
			}
			set
			{
				if ((this._tieudehoso != value))
				{
					this.OntieudehosoChanging(value);
					this.SendPropertyChanging();
					this._tieudehoso = value;
					this.SendPropertyChanged("tieudehoso");
					this.OntieudehosoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoilaphoso", DbType="VarChar(50)")]
		public string nguoilaphoso
		{
			get
			{
				return this._nguoilaphoso;
			}
			set
			{
				if ((this._nguoilaphoso != value))
				{
					this.OnnguoilaphosoChanging(value);
					this.SendPropertyChanging();
					this._nguoilaphoso = value;
					this.SendPropertyChanged("nguoilaphoso");
					this.OnnguoilaphosoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this.OnngaybatdauChanging(value);
					this.SendPropertyChanging();
					this._ngaybatdau = value;
					this.SendPropertyChanged("ngaybatdau");
					this.OnngaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this.OnngayketthucChanging(value);
					this.SendPropertyChanging();
					this._ngayketthuc = value;
					this.SendPropertyChanged("ngayketthuc");
					this.OnngayketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soto", DbType="VarChar(20)")]
		public string soto
		{
			get
			{
				return this._soto;
			}
			set
			{
				if ((this._soto != value))
				{
					this.OnsotoChanging(value);
					this.SendPropertyChanging();
					this._soto = value;
					this.SendPropertyChanged("soto");
					this.OnsotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaivanbandenhaydi", DbType="TinyInt")]
		public System.Nullable<byte> loaivanbandenhaydi
		{
			get
			{
				return this._loaivanbandenhaydi;
			}
			set
			{
				if ((this._loaivanbandenhaydi != value))
				{
					this.OnloaivanbandenhaydiChanging(value);
					this.SendPropertyChanging();
					this._loaivanbandenhaydi = value;
					this.SendPropertyChanged("loaivanbandenhaydi");
					this.OnloaivanbandenhaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO_CHITIETHOSO", Storage="_CHITIETHOSOs", ThisKey="id_hoso", OtherKey="idhoso")]
		public EntitySet<CHITIETHOSO> CHITIETHOSOs
		{
			get
			{
				return this._CHITIETHOSOs;
			}
			set
			{
				this._CHITIETHOSOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOSOs(CHITIETHOSO entity)
		{
			this.SendPropertyChanging();
			entity.HOSO = this;
		}
		
		private void detach_CHITIETHOSOs(CHITIETHOSO entity)
		{
			this.SendPropertyChanging();
			entity.HOSO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNV;
		
		private string _hoten;
		
		private string _matkhau;
		
		private string _email;
		
		private string _dienthoai;
		
		private EntitySet<CHITIETHOSO> _CHITIETHOSOs;
		
		private EntitySet<VANBANDI> _VANBANDIs;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
		private EntitySet<VANBANDEN> _VANBANDENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(int value);
    partial void OnmaNVChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._CHITIETHOSOs = new EntitySet<CHITIETHOSO>(new Action<CHITIETHOSO>(this.attach_CHITIETHOSOs), new Action<CHITIETHOSO>(this.detach_CHITIETHOSOs));
			this._VANBANDIs = new EntitySet<VANBANDI>(new Action<VANBANDI>(this.attach_VANBANDIs), new Action<VANBANDI>(this.detach_VANBANDIs));
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			this._VANBANDENs = new EntitySet<VANBANDEN>(new Action<VANBANDEN>(this.attach_VANBANDENs), new Action<VANBANDEN>(this.detach_VANBANDENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="VarChar(100)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(100)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(50)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CHITIETHOSO", Storage="_CHITIETHOSOs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<CHITIETHOSO> CHITIETHOSOs
		{
			get
			{
				return this._CHITIETHOSOs;
			}
			set
			{
				this._CHITIETHOSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VANBANDI", Storage="_VANBANDIs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<VANBANDI> VANBANDIs
		{
			get
			{
				return this._VANBANDIs;
			}
			set
			{
				this._VANBANDIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="maNV", OtherKey="manhanvien")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VANBANDEN", Storage="_VANBANDENs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<VANBANDEN> VANBANDENs
		{
			get
			{
				return this._VANBANDENs;
			}
			set
			{
				this._VANBANDENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOSOs(CHITIETHOSO entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_CHITIETHOSOs(CHITIETHOSO entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_VANBANDIs(VANBANDI entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_VANBANDIs(VANBANDI entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_VANBANDENs(VANBANDEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_VANBANDENs(VANBANDEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maquyen;
		
		private System.Nullable<int> _manhanvien;
		
		private System.Nullable<int> _maphongban;
		
		private System.Nullable<bool> _xem;
		
		private System.Nullable<bool> _sua;
		
		private System.Nullable<bool> _xoa;
		
		private System.Nullable<bool> _inan;
		
		private System.Nullable<bool> _export;
		
		private System.Nullable<bool> _import;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHONGBAN> _PHONGBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaquyenChanging(int value);
    partial void OnmaquyenChanged();
    partial void OnmanhanvienChanging(System.Nullable<int> value);
    partial void OnmanhanvienChanged();
    partial void OnmaphongbanChanging(System.Nullable<int> value);
    partial void OnmaphongbanChanged();
    partial void OnxemChanging(System.Nullable<bool> value);
    partial void OnxemChanged();
    partial void OnsuaChanging(System.Nullable<bool> value);
    partial void OnsuaChanged();
    partial void OnxoaChanging(System.Nullable<bool> value);
    partial void OnxoaChanged();
    partial void OninanChanging(System.Nullable<bool> value);
    partial void OninanChanged();
    partial void OnexportChanging(System.Nullable<bool> value);
    partial void OnexportChanged();
    partial void OnimportChanging(System.Nullable<bool> value);
    partial void OnimportChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHONGBAN = default(EntityRef<PHONGBAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maquyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maquyen
		{
			get
			{
				return this._maquyen;
			}
			set
			{
				if ((this._maquyen != value))
				{
					this.OnmaquyenChanging(value);
					this.SendPropertyChanging();
					this._maquyen = value;
					this.SendPropertyChanged("maquyen");
					this.OnmaquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="Int")]
		public System.Nullable<int> manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphongban", DbType="Int")]
		public System.Nullable<int> maphongban
		{
			get
			{
				return this._maphongban;
			}
			set
			{
				if ((this._maphongban != value))
				{
					if (this._PHONGBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongbanChanging(value);
					this.SendPropertyChanging();
					this._maphongban = value;
					this.SendPropertyChanged("maphongban");
					this.OnmaphongbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xem", DbType="Bit")]
		public System.Nullable<bool> xem
		{
			get
			{
				return this._xem;
			}
			set
			{
				if ((this._xem != value))
				{
					this.OnxemChanging(value);
					this.SendPropertyChanging();
					this._xem = value;
					this.SendPropertyChanged("xem");
					this.OnxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sua", DbType="Bit")]
		public System.Nullable<bool> sua
		{
			get
			{
				return this._sua;
			}
			set
			{
				if ((this._sua != value))
				{
					this.OnsuaChanging(value);
					this.SendPropertyChanging();
					this._sua = value;
					this.SendPropertyChanged("sua");
					this.OnsuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xoa", DbType="Bit")]
		public System.Nullable<bool> xoa
		{
			get
			{
				return this._xoa;
			}
			set
			{
				if ((this._xoa != value))
				{
					this.OnxoaChanging(value);
					this.SendPropertyChanging();
					this._xoa = value;
					this.SendPropertyChanged("xoa");
					this.OnxoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inan", DbType="Bit")]
		public System.Nullable<bool> inan
		{
			get
			{
				return this._inan;
			}
			set
			{
				if ((this._inan != value))
				{
					this.OninanChanging(value);
					this.SendPropertyChanging();
					this._inan = value;
					this.SendPropertyChanged("inan");
					this.OninanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export", DbType="Bit")]
		public System.Nullable<bool> export
		{
			get
			{
				return this._export;
			}
			set
			{
				if ((this._export != value))
				{
					this.OnexportChanging(value);
					this.SendPropertyChanging();
					this._export = value;
					this.SendPropertyChanged("export");
					this.OnexportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import", DbType="Bit")]
		public System.Nullable<bool> import
		{
			get
			{
				return this._import;
			}
			set
			{
				if ((this._import != value))
				{
					this.OnimportChanging(value);
					this.SendPropertyChanging();
					this._import = value;
					this.SendPropertyChanged("import");
					this.OnimportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHANQUYEN", Storage="_NHANVIEN", ThisKey="manhanvien", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._manhanvien = value.maNV;
					}
					else
					{
						this._manhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_PHANQUYEN", Storage="_PHONGBAN", ThisKey="maphongban", OtherKey="maphongban", IsForeignKey=true)]
		public PHONGBAN PHONGBAN
		{
			get
			{
				return this._PHONGBAN.Entity;
			}
			set
			{
				PHONGBAN previousValue = this._PHONGBAN.Entity;
				if (((previousValue != value) 
							|| (this._PHONGBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGBAN.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._PHONGBAN.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._maphongban = value.maphongban;
					}
					else
					{
						this._maphongban = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHONGBAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maphongban;
		
		private string _tenphongban;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongbanChanging(int value);
    partial void OnmaphongbanChanged();
    partial void OntenphongbanChanging(string value);
    partial void OntenphongbanChanged();
    #endregion
		
		public PHONGBAN()
		{
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphongban", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maphongban
		{
			get
			{
				return this._maphongban;
			}
			set
			{
				if ((this._maphongban != value))
				{
					this.OnmaphongbanChanging(value);
					this.SendPropertyChanging();
					this._maphongban = value;
					this.SendPropertyChanged("maphongban");
					this.OnmaphongbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphongban", DbType="VarChar(100)")]
		public string tenphongban
		{
			get
			{
				return this._tenphongban;
			}
			set
			{
				if ((this._tenphongban != value))
				{
					this.OntenphongbanChanging(value);
					this.SendPropertyChanging();
					this._tenphongban = value;
					this.SendPropertyChanged("tenphongban");
					this.OntenphongbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="maphongban", OtherKey="maphongban")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDEN")]
	public partial class VANBANDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sovanbanden;
		
		private string _kyhieuvanban;
		
		private System.Nullable<System.DateTime> _ngayden;
		
		private System.Nullable<System.DateTime> _ngaybanhanh;
		
		private string _coquan;
		
		private string _trichyeu;
		
		private string _linhvuc;
		
		private string _loaivanban;
		
		private string _dokhan;
		
		private string _domat;
		
		private string _filedinhkem;
		
		private System.Nullable<byte> _xuly;
		
		private string _quyenxem;
		
		private string _lanhdaophancong;
		
		private string _ykienchidao;
		
		private System.Nullable<System.DateTime> _ngaythuchien;
		
		private string _phongbanxulychinh;
		
		private string _phongbanphoihop;
		
		private System.Nullable<System.DateTime> _hanxuly;
		
		private System.Nullable<System.DateTime> _ngayxuly;
		
		private string _nguoixuly;
		
		private string _sovanbannam;
		
		private string _sotrang;
		
		private System.Nullable<int> _maNV;
		
		private EntitySet<DANHMUC> _DANHMUCs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsovanbandenChanging(int value);
    partial void OnsovanbandenChanged();
    partial void OnkyhieuvanbanChanging(string value);
    partial void OnkyhieuvanbanChanged();
    partial void OnngaydenChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydenChanged();
    partial void OnngaybanhanhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybanhanhChanged();
    partial void OncoquanChanging(string value);
    partial void OncoquanChanged();
    partial void OntrichyeuChanging(string value);
    partial void OntrichyeuChanged();
    partial void OnlinhvucChanging(string value);
    partial void OnlinhvucChanged();
    partial void OnloaivanbanChanging(string value);
    partial void OnloaivanbanChanged();
    partial void OndokhanChanging(string value);
    partial void OndokhanChanged();
    partial void OndomatChanging(string value);
    partial void OndomatChanged();
    partial void OnfiledinhkemChanging(string value);
    partial void OnfiledinhkemChanged();
    partial void OnxulyChanging(System.Nullable<byte> value);
    partial void OnxulyChanged();
    partial void OnquyenxemChanging(string value);
    partial void OnquyenxemChanged();
    partial void OnlanhdaophancongChanging(string value);
    partial void OnlanhdaophancongChanged();
    partial void OnykienchidaoChanging(string value);
    partial void OnykienchidaoChanged();
    partial void OnngaythuchienChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythuchienChanged();
    partial void OnphongbanxulychinhChanging(string value);
    partial void OnphongbanxulychinhChanged();
    partial void OnphongbanphoihopChanging(string value);
    partial void OnphongbanphoihopChanged();
    partial void OnhanxulyChanging(System.Nullable<System.DateTime> value);
    partial void OnhanxulyChanged();
    partial void OnngayxulyChanging(System.Nullable<System.DateTime> value);
    partial void OnngayxulyChanged();
    partial void OnnguoixulyChanging(string value);
    partial void OnnguoixulyChanged();
    partial void OnsovanbannamChanging(string value);
    partial void OnsovanbannamChanged();
    partial void OnsotrangChanging(string value);
    partial void OnsotrangChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    #endregion
		
		public VANBANDEN()
		{
			this._DANHMUCs = new EntitySet<DANHMUC>(new Action<DANHMUC>(this.attach_DANHMUCs), new Action<DANHMUC>(this.detach_DANHMUCs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sovanbanden", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sovanbanden
		{
			get
			{
				return this._sovanbanden;
			}
			set
			{
				if ((this._sovanbanden != value))
				{
					this.OnsovanbandenChanging(value);
					this.SendPropertyChanging();
					this._sovanbanden = value;
					this.SendPropertyChanged("sovanbanden");
					this.OnsovanbandenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kyhieuvanban", DbType="VarChar(50)")]
		public string kyhieuvanban
		{
			get
			{
				return this._kyhieuvanban;
			}
			set
			{
				if ((this._kyhieuvanban != value))
				{
					this.OnkyhieuvanbanChanging(value);
					this.SendPropertyChanging();
					this._kyhieuvanban = value;
					this.SendPropertyChanged("kyhieuvanban");
					this.OnkyhieuvanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="Date")]
		public System.Nullable<System.DateTime> ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this.OnngaydenChanging(value);
					this.SendPropertyChanging();
					this._ngayden = value;
					this.SendPropertyChanged("ngayden");
					this.OnngaydenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybanhanh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybanhanh
		{
			get
			{
				return this._ngaybanhanh;
			}
			set
			{
				if ((this._ngaybanhanh != value))
				{
					this.OnngaybanhanhChanging(value);
					this.SendPropertyChanging();
					this._ngaybanhanh = value;
					this.SendPropertyChanged("ngaybanhanh");
					this.OnngaybanhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coquan", DbType="VarChar(50)")]
		public string coquan
		{
			get
			{
				return this._coquan;
			}
			set
			{
				if ((this._coquan != value))
				{
					this.OncoquanChanging(value);
					this.SendPropertyChanging();
					this._coquan = value;
					this.SendPropertyChanged("coquan");
					this.OncoquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trichyeu", DbType="VarChar(250)")]
		public string trichyeu
		{
			get
			{
				return this._trichyeu;
			}
			set
			{
				if ((this._trichyeu != value))
				{
					this.OntrichyeuChanging(value);
					this.SendPropertyChanging();
					this._trichyeu = value;
					this.SendPropertyChanged("trichyeu");
					this.OntrichyeuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linhvuc", DbType="VarChar(50)")]
		public string linhvuc
		{
			get
			{
				return this._linhvuc;
			}
			set
			{
				if ((this._linhvuc != value))
				{
					this.OnlinhvucChanging(value);
					this.SendPropertyChanging();
					this._linhvuc = value;
					this.SendPropertyChanged("linhvuc");
					this.OnlinhvucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaivanban", DbType="VarChar(50)")]
		public string loaivanban
		{
			get
			{
				return this._loaivanban;
			}
			set
			{
				if ((this._loaivanban != value))
				{
					this.OnloaivanbanChanging(value);
					this.SendPropertyChanging();
					this._loaivanban = value;
					this.SendPropertyChanged("loaivanban");
					this.OnloaivanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dokhan", DbType="VarChar(50)")]
		public string dokhan
		{
			get
			{
				return this._dokhan;
			}
			set
			{
				if ((this._dokhan != value))
				{
					this.OndokhanChanging(value);
					this.SendPropertyChanging();
					this._dokhan = value;
					this.SendPropertyChanged("dokhan");
					this.OndokhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domat", DbType="VarChar(50)")]
		public string domat
		{
			get
			{
				return this._domat;
			}
			set
			{
				if ((this._domat != value))
				{
					this.OndomatChanging(value);
					this.SendPropertyChanging();
					this._domat = value;
					this.SendPropertyChanged("domat");
					this.OndomatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filedinhkem", DbType="VarChar(250)")]
		public string filedinhkem
		{
			get
			{
				return this._filedinhkem;
			}
			set
			{
				if ((this._filedinhkem != value))
				{
					this.OnfiledinhkemChanging(value);
					this.SendPropertyChanging();
					this._filedinhkem = value;
					this.SendPropertyChanged("filedinhkem");
					this.OnfiledinhkemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuly", DbType="TinyInt")]
		public System.Nullable<byte> xuly
		{
			get
			{
				return this._xuly;
			}
			set
			{
				if ((this._xuly != value))
				{
					this.OnxulyChanging(value);
					this.SendPropertyChanging();
					this._xuly = value;
					this.SendPropertyChanged("xuly");
					this.OnxulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenxem", DbType="VarChar(100)")]
		public string quyenxem
		{
			get
			{
				return this._quyenxem;
			}
			set
			{
				if ((this._quyenxem != value))
				{
					this.OnquyenxemChanging(value);
					this.SendPropertyChanging();
					this._quyenxem = value;
					this.SendPropertyChanged("quyenxem");
					this.OnquyenxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanhdaophancong", DbType="VarChar(50)")]
		public string lanhdaophancong
		{
			get
			{
				return this._lanhdaophancong;
			}
			set
			{
				if ((this._lanhdaophancong != value))
				{
					this.OnlanhdaophancongChanging(value);
					this.SendPropertyChanging();
					this._lanhdaophancong = value;
					this.SendPropertyChanged("lanhdaophancong");
					this.OnlanhdaophancongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ykienchidao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ykienchidao
		{
			get
			{
				return this._ykienchidao;
			}
			set
			{
				if ((this._ykienchidao != value))
				{
					this.OnykienchidaoChanging(value);
					this.SendPropertyChanging();
					this._ykienchidao = value;
					this.SendPropertyChanged("ykienchidao");
					this.OnykienchidaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythuchien", DbType="Date")]
		public System.Nullable<System.DateTime> ngaythuchien
		{
			get
			{
				return this._ngaythuchien;
			}
			set
			{
				if ((this._ngaythuchien != value))
				{
					this.OnngaythuchienChanging(value);
					this.SendPropertyChanging();
					this._ngaythuchien = value;
					this.SendPropertyChanged("ngaythuchien");
					this.OnngaythuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongbanxulychinh", DbType="VarChar(100)")]
		public string phongbanxulychinh
		{
			get
			{
				return this._phongbanxulychinh;
			}
			set
			{
				if ((this._phongbanxulychinh != value))
				{
					this.OnphongbanxulychinhChanging(value);
					this.SendPropertyChanging();
					this._phongbanxulychinh = value;
					this.SendPropertyChanged("phongbanxulychinh");
					this.OnphongbanxulychinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongbanphoihop", DbType="VarChar(100)")]
		public string phongbanphoihop
		{
			get
			{
				return this._phongbanphoihop;
			}
			set
			{
				if ((this._phongbanphoihop != value))
				{
					this.OnphongbanphoihopChanging(value);
					this.SendPropertyChanging();
					this._phongbanphoihop = value;
					this.SendPropertyChanged("phongbanphoihop");
					this.OnphongbanphoihopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanxuly", DbType="Date")]
		public System.Nullable<System.DateTime> hanxuly
		{
			get
			{
				return this._hanxuly;
			}
			set
			{
				if ((this._hanxuly != value))
				{
					this.OnhanxulyChanging(value);
					this.SendPropertyChanging();
					this._hanxuly = value;
					this.SendPropertyChanged("hanxuly");
					this.OnhanxulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuly", DbType="Date")]
		public System.Nullable<System.DateTime> ngayxuly
		{
			get
			{
				return this._ngayxuly;
			}
			set
			{
				if ((this._ngayxuly != value))
				{
					this.OnngayxulyChanging(value);
					this.SendPropertyChanging();
					this._ngayxuly = value;
					this.SendPropertyChanged("ngayxuly");
					this.OnngayxulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoixuly", DbType="VarChar(50)")]
		public string nguoixuly
		{
			get
			{
				return this._nguoixuly;
			}
			set
			{
				if ((this._nguoixuly != value))
				{
					this.OnnguoixulyChanging(value);
					this.SendPropertyChanging();
					this._nguoixuly = value;
					this.SendPropertyChanged("nguoixuly");
					this.OnnguoixulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sovanbannam", DbType="VarChar(100)")]
		public string sovanbannam
		{
			get
			{
				return this._sovanbannam;
			}
			set
			{
				if ((this._sovanbannam != value))
				{
					this.OnsovanbannamChanging(value);
					this.SendPropertyChanging();
					this._sovanbannam = value;
					this.SendPropertyChanged("sovanbannam");
					this.OnsovanbannamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotrang", DbType="VarChar(10)")]
		public string sotrang
		{
			get
			{
				return this._sotrang;
			}
			set
			{
				if ((this._sotrang != value))
				{
					this.OnsotrangChanging(value);
					this.SendPropertyChanging();
					this._sotrang = value;
					this.SendPropertyChanged("sotrang");
					this.OnsotrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VANBANDEN_DANHMUC", Storage="_DANHMUCs", ThisKey="sovanbanden", OtherKey="idvanbanden")]
		public EntitySet<DANHMUC> DANHMUCs
		{
			get
			{
				return this._DANHMUCs;
			}
			set
			{
				this._DANHMUCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_VANBANDEN", Storage="_NHANVIEN", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.VANBANDENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.VANBANDENs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHMUCs(DANHMUC entity)
		{
			this.SendPropertyChanging();
			entity.VANBANDEN = this;
		}
		
		private void detach_DANHMUCs(DANHMUC entity)
		{
			this.SendPropertyChanging();
			entity.VANBANDEN = null;
		}
	}
}
#pragma warning restore 1591
